# Generated by Django 4.2.4 on 2023-11-02 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mail_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_email', models.EmailField(max_length=50)),
                ('subject', models.CharField(default='none', max_length=500)),
                ('msg', models.TextField(default='none')),
                ('date', models.DateField(auto_now=True)),
                ('read', models.BooleanField(default=False)),
                ('reply', models.BooleanField(default=False)),
                ('reply_msg', models.TextField(default='none')),
                ('r_type', models.BooleanField(default=False)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
