# Generated by Django 4.2.4 on 2023-11-03 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail_data',
            old_name='email',
            new_name='user',
        ),
    ]
