# Generated by Django 4.2.4 on 2023-11-03 11:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0002_rename_email_mail_data_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail_data',
            name='u_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
    ]
