# Generated by Django 4.2.4 on 2023-11-04 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0003_mail_data_u_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail_data',
            old_name='r_type',
            new_name='verify',
        ),
    ]
