# Generated by Django 4.2.4 on 2023-11-04 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0004_rename_r_type_mail_data_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail_data',
            name='verify',
        ),
    ]
